### PR TITLE
Service refactor

### PR DESCRIPTION
**Pull request by mlos100**
Update data model and services by changing RecordMatchConfiguration to RecordMatchContext and requiring record set(s), matching mode, and record match system interface to be provided when creating a record match run.  (Changed name of RecordMatchJob back to RecordMatchRun)

### CODE REVIEW

**Comment by eedrummer** [comment]
The test suite is failing on my machine:

```
℞ ptmatch (service-refactor) $ go test $(go list ./... | grep -v /vendor/)      # github.com/mitre/ptmatch/controllers
controllers/record_match_run_test.go:101: cannot use recMatchContext (type *"github.com/mitre/ptmatch/models".RecordMatchContext) as type *"github.com/mitre/ptmatch/models".RecordMatchRun in argument to controller.newRecordMatchRequest
controllers/record_match_run_test.go:135: cannot use recMatchContext (type *"github.com/mitre/ptmatch/models".RecordMatchContext) as type *"github.com/mitre/ptmatch/models".RecordMatchRun in argument to controller.newRecordMatchRequest
controllers/record_match_run_test.go:163: cannot use recMatchContext (type *"github.com/mitre/ptmatch/models".RecordMatchContext) as type *"github.com/mitre/ptmatch/models".RecordMatchRun in argument to controller.newMessageHeader
```

Am I doing something wrong. Also, I'm going to work on getting this repo hooked up to Travis.

**Comment by mlos100** [comment]
I wasn't running go test properly.  Am working to address.  Unfortunately, the tests in controllers assumes mongoDB is available so I don't think it will work with Travis.

**Comment by eedrummer** [comment]
We run MongoDB on Travis all of the time. It is not a problem.

**Comment by mlos100** [comment]
I copied and pasted a bit of the travis file from ecqm.  travis-ci doesn't recognize this as one of my projects. so I won't be able to do anything on that side of things.

**Pull request merged**
